name: Format check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'TP4/**'

jobs:
  precommit:
    if: github.head_ref == 'TP_4'
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format cppcheck

    - name: Run clang-format
      run: |
        find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' | xargs clang-format -i
        git diff --exit-code
